require_relative 'authenticate_account'
require_relative 'find_course_auth'
require_relative 'find_course_video'
require_relative 'create_folder_for_course'
require_relative 'create_file_for_folder'
require_relative 'find_video_record'
require_relative 'find_file_content'
